name: medianest-dev

services:
  medianest:
    container_name: medianest
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
      - DATABASE_URL=postgresql://postgres:postgres@database/medianest
    volumes:
      - ./data:/app/data
    ports:
      - 5000:5000
    depends_on:
      database:
        condition: service_started
    restart: unless-stopped

  database:
    image: postgres:17
    container_name: medianest_postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: medianest
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      TZ: Asia/Shanghai
    volumes:
      - medianest-db-data:/var/lib/postgresql/data/
    healthcheck:
      test: [ 'CMD', 'pg_isready', '-U', 'postgres', '-d', 'postgres' ]
      interval: 5s
      timeout: 10s
      retries: 5

volumes:
  medianest-db-data:
